services:
    # --- PHP Application Service ---
    app:
        image: ${DOCKERHUB_USERNAME}/alpesone-test:latest
        container_name: alpesone-app
        restart: unless-stopped
        environment:
            - APP_NAME=Alpes One Test
            - APP_ENV=${APP_ENV}
            - APP_KEY=${APP_KEY}
            - APP_DEBUG=${APP_DEBUG}
            - APP_URL=${APP_URL}
            - LOG_CHANNEL=${LOG_CHANNEL}
            - LOG_LEVEL=${LOG_LEVEL}
            - DB_CONNECTION=${DB_CONNECTION}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - alpesone_network
        healthcheck:
            test: [ "CMD", "php", "artisan", "tinker", "--execute=echo 'OK'" ]
            interval: 30s
            timeout: 10s
            retries: 3

    # --- Web server (Nginx) to serve the application ---
    nginx:
        image: nginx:1.29-alpine
        container_name: alpesone-nginx
        restart: unless-stopped
        volumes:
            - ./.docker/nginx:/etc/nginx/conf.d
            - ./.docker/letsencrypt/etc:/etc/letsencrypt
            - ./.docker/letsencrypt/var/log:/var/log/letsencrypt
            - .:/var/www/html
        depends_on:
            app:
                condition: service_healthy
        networks:
            - alpesone_network
        ports:
            - "80:80"
            - "443:443"

    # --- Database Service (MySQL) ---
    db-mysql:
        image: mysql:8.0
        container_name: db-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        networks:
            - alpesone_network
        ports:
            - '3306:3306'
        volumes:
            - mysql_data:/var/lib/mysql
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    mysql_data:
        driver: local

networks:
    alpesone_network:
        driver: bridge
