services:
  # --- PHP Application Service ---
  app:
    build:
      context: .
    container_name: alpesone-app
    restart: unless-stopped
    depends_on:
      db-mysql:
        condition: service_healthy
    networks:
      - local_network
    healthcheck:
      test: [ "CMD", "php", "artisan", "tinker", "--execute=echo 'OK'" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # --- Web server (Nginx) to serve the application ---
  nginx:
    image: nginx:1.29-alpine
    container_name: alpesone-nginx
    restart: unless-stopped
    volumes:
      - ./.docker/nginx/local:/etc/nginx/conf.d
    depends_on:
      app:
        condition: service_healthy
    networks:
      - local_network
    ports:
      - "80:80"

  # --- Database Service (MySQL) ---
  db-mysql:
    image: mysql:8.0
    container_name: db-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    networks:
      - local_network
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
    driver: local

networks:
  local_network:
    driver: bridge
